
server:
  port: 8089

spring:
  application:
    name: demo-eureka-client-c

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true # Optional, for preferring IP address in registration
